# Generated by Django 4.2.14 on 2025-07-25 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(blank=True, help_text="User's name.", max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, help_text="User's last name.", max_length=100, null=True)),
                ('email', models.EmailField(help_text='Email address (used as login).', max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, help_text="User's phone number.", max_length=30, null=True)),
                ('bio', models.TextField(blank=True, help_text='Short bio or introduction (optional).', null=True)),
                ('is_event_organizer', models.BooleanField(blank=True, help_text='True if the user has created events that have been published.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the user account was created.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.')),
                ('is_staff', models.BooleanField(default=False, help_text='For Django admin compatibility (not used in app logic).')),
                ('is_superuser', models.BooleanField(default=False, help_text='For Django admin compatibility (not used in app logic).')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccessibilityFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Feature name (unique, e.g., Wheelchair access).', max_length=100, unique=True)),
                ('description', models.CharField(blank=True, help_text='Feature description.', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (unique).', max_length=100, unique=True)),
                ('description', models.CharField(help_text='Short description of the category.', max_length=255, null=True)),
                ('image_path', models.CharField(help_text='Path to the category icon or image (optional). Use ImageField for file storage.', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Currency code or abbreviation (e.g., CRC, USD).', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Event name.', max_length=150)),
                ('description', models.TextField(help_text='Full event description (can use markdown/HTML if needed).')),
                ('start_datetime', models.DateTimeField(help_text='Event start date and time.')),
                ('end_datetime', models.DateTimeField(blank=True, help_text='Event end date and time (optional).', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Event price. Null if free.', max_digits=10, null=True)),
                ('ticket_link', models.CharField(blank=True, help_text='URL for ticket sales (optional).', max_length=255, null=True)),
                ('contact_email', models.CharField(blank=True, help_text='Contact email for the event.', max_length=100, null=True)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number.', max_length=30, null=True)),
                ('address', models.CharField(help_text='Physical address or venue.', max_length=255)),
                ('map_location', models.CharField(blank=True, help_text='Google Maps URL or coordinates (optional).', max_length=255, null=True)),
                ('is_event_approved', models.BooleanField(default=False, help_text='Event approval status (set by admin).')),
                ('last_request_change_reason', models.CharField(blank=True, help_text='Reason for latest change request (optional).', max_length=300, null=True)),
                ('delete_reason', models.CharField(blank=True, help_text='Reason for deletion (optional, for auditing).', max_length=300, null=True)),
                ('is_event_active', models.BooleanField(default=True, help_text='Whether the event is currently active (soft delete).')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of event creation.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp.', null=True)),
                ('event_banner_path', models.CharField(blank=True, help_text='Path to the event banner image (optional).', max_length=255, null=True)),
                ('approved_by', models.ForeignKey(help_text='Admin user who approved the event.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_events', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Event category.', on_delete=django.db.models.deletion.PROTECT, to='events.category')),
                ('created_by', models.ForeignKey(help_text='User who created the event.', on_delete=django.db.models.deletion.PROTECT, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(help_text='Currency for event price.', null=True, on_delete=django.db.models.deletion.PROTECT, to='events.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the organization (unique).', max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, help_text="Organization's contact phone number.", max_length=30, null=True)),
                ('email', models.CharField(blank=True, help_text="Organization's contact email.", max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short role name (e.g., Administrator, Visitor).', max_length=45)),
                ('description', models.CharField(blank=True, help_text='Optional description for the role.', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='The text content of the comment.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of comment creation.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp.', null=True)),
                ('image_path', models.CharField(blank=True, help_text='Path to the comment image (optional).', max_length=255, null=True)),
                ('event', models.ForeignKey(help_text='Event being commented on.', on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('user', models.ForeignKey(help_text='User who made the comment.', on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization the user belongs to (optional).', null=True, on_delete=django.db.models.deletion.PROTECT, to='events.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(help_text="User's role (for access control).", on_delete=django.db.models.deletion.PROTECT, to='events.userrole'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(help_text='Related event.', on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('user', models.ForeignKey(help_text='Related user.', on_delete=django.db.models.deletion.CASCADE, related_name='user_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='EventAccessibilityFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessibility_feature', models.ForeignKey(help_text='Associated accessibility feature.', on_delete=django.db.models.deletion.CASCADE, to='events.accessibilityfeature')),
                ('event', models.ForeignKey(help_text='Event with accessibility feature.', on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'unique_together': {('event', 'accessibility_feature')},
            },
        ),
    ]
