# Generated by Django 4.2.14 on 2025-07-12 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Feature name (unique, e.g., Wheelchair access).', max_length=100, null=True, unique=True)),
                ('description', models.CharField(blank=True, help_text='Feature description.', max_length=500, null=True)),
                ('image', models.BinaryField(blank=True, help_text='Optional icon/image. Use ImageField for uploads.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Currency code or abbreviation (e.g., CRC, USD).', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the organization (unique).', max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, help_text="Organization's contact phone number.", max_length=30, null=True)),
                ('email', models.CharField(blank=True, help_text="Organization's contact email.", max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short role name (e.g., Administrator, Visitor).', max_length=45)),
                ('description', models.CharField(blank=True, help_text='Optional description for the role.', max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='No description', help_text='Short description of the category.', max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.BinaryField(blank=True, help_text='Category icon or image (optional). Use ImageField for file storage.', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Category name (unique).', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="User's first name.", max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, help_text="User's last name.", max_length=100, null=True)),
                ('email', models.CharField(help_text='Email address (used as login).', max_length=100, unique=True)),
                ('password_hash', models.CharField(help_text='Hashed user password (never store plaintext).', max_length=100)),
                ('phone', models.CharField(blank=True, help_text="User's phone number.", max_length=30, null=True)),
                ('bio', models.TextField(blank=True, help_text='Short bio or introduction (optional).', null=True)),
                ('is_event_organizer', models.BooleanField(blank=True, help_text='True if the user can create events.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the user account was created.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp.', null=True)),
                ('organization', models.ForeignKey(help_text='Organization the user belongs to.', on_delete=django.db.models.deletion.PROTECT, to='events.organization')),
                ('role', models.ForeignKey(help_text="User's role (for access control).", on_delete=django.db.models.deletion.PROTECT, to='events.userrole')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Event name.', max_length=150)),
                ('description', models.TextField(help_text='Full event description (can use markdown/HTML if needed).')),
                ('start_datetime', models.DateTimeField(help_text='Event start date and time.')),
                ('end_datetime', models.DateTimeField(blank=True, help_text='Event end date and time (optional).', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Event price. Null if free.', max_digits=10, null=True)),
                ('ticket_link', models.CharField(blank=True, help_text='URL for ticket sales (optional).', max_length=255, null=True)),
                ('contact_email', models.CharField(blank=True, help_text='Contact email for the event.', max_length=100, null=True)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number.', max_length=30, null=True)),
                ('address', models.CharField(help_text='Physical address or venue.', max_length=255)),
                ('map_location', models.CharField(blank=True, help_text='Google Maps URL or coordinates (optional).', max_length=255, null=True)),
                ('event_banner', models.BinaryField(blank=True, help_text='Banner image (optional). Use ImageField for uploads.', null=True)),
                ('is_event_approved', models.BooleanField(default=False, help_text='Event approval status (set by admin).')),
                ('last_request_change_reason', models.CharField(blank=True, help_text='Reason for latest change request (optional).', max_length=300, null=True)),
                ('delete_reason', models.CharField(blank=True, help_text='Reason for deletion (optional, for auditing).', max_length=300, null=True)),
                ('is_event_active', models.BooleanField(default=True, help_text='Whether the event is currently active (soft delete).')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of event creation.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp.', null=True)),
                ('approved_by', models.ForeignKey(help_text='Admin user who approved the event.', on_delete=django.db.models.deletion.PROTECT, related_name='approved_events', to='events.user')),
                ('category', models.ForeignKey(help_text='Event category.', on_delete=django.db.models.deletion.PROTECT, to='events.category')),
                ('created_by', models.ForeignKey(help_text='User who created the event.', on_delete=django.db.models.deletion.PROTECT, related_name='created_events', to='events.user')),
                ('currency', models.ForeignKey(help_text='Currency for event price.', on_delete=django.db.models.deletion.PROTECT, to='events.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField(blank=True, help_text='Optional image. Use ImageField for user uploads.', null=True)),
                ('comment', models.TextField(help_text='The text content of the comment.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of comment creation.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp.', null=True)),
                ('event', models.ForeignKey(help_text='Event being commented on.', on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('user', models.ForeignKey(help_text='User who made the comment.', on_delete=django.db.models.deletion.CASCADE, to='events.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(help_text='Related event.', on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('user', models.ForeignKey(help_text='Related user.', on_delete=django.db.models.deletion.CASCADE, to='events.user')),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='EventAccessibilityFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessibility_feature', models.ForeignKey(help_text='Associated accessibility feature.', on_delete=django.db.models.deletion.CASCADE, to='events.accessibilityfeature')),
                ('event', models.ForeignKey(help_text='Event with accessibility feature.', on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'unique_together': {('event', 'accessibility_feature')},
            },
        ),
    ]
